version: '3'
services:

  oyente:
    build:
      context: ./oyente
    volumes:
        - ./contracts:/contracts
    ports:
      - 3000:3000
  mythril:
    build:
      context: ./mythril
    volumes:
        - ./contracts:/contracts
  manticore:
    build:
      context: ./manticore
    volumes:
        - ./contracts:/contracts
