version: '3'
services:
  oyente:
    image: luongnguyen/oyente
    # build:
    #   context: ./oyente
    volumes:
        - ./contracts:/contracts
    ports:
      - 3000:3000
  mythril:
    build:
      context: ./mythril
    volumes:
        - ./mythril:/mythril
    ports:
        - 8080:8080
    command: >
      sh -c 'cd mythril/api;npm i;npm start'
  manticore:
    build:
      context: ./manticore
    volumes:
        - ./contracts:/contracts
