version: '3'
services:
  oyente:
    image: luongnguyen/oyente
    # build:
    #   context: ./oyente
    volumes:
        - ./oyente:/oyente
    ports:
      - 3030:8080
      - 3000:3000
    command: >
      sh -c 'cd web;bundle install;bin/rails server'
  mythril:
    build:
      context: ./mythril
    volumes:
        - ./mythril:/mythril
    ports:
        - 4000:8080
    command: >
      sh -c 'cd mythril/api;npm i;npm start'
  # manticore:
  #   build:
  #     context: ./manticore
  #   volumes:
  #       - ./contracts:/contracts
